### ISSUE TITLE
Erreur à l'installation du à des versions dask et dask[dataframe] différentes

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/gn_module_import#184]
L'installation du module sur une installation fraîche soulève des erreurs en lien avec des versions  `dask` et `dask[dataframe]` différentes. Passer `dask` en version 2.0.0 (comme `dask[dataframe]` résoud le problème).

```
[...]
INFO: pip is looking at multiple versions of cloudpickle to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install dask==0.19.1 and dask[dataframe]==2.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested dask==0.19.1
    dask[dataframe] 2.0.0 depends on dask 2.0.0 (from https://files.pythonhosted.org/packages/bd/c0/ac42b459c77223b503fbfcc030850524c95170d27a5bcbf9ffb6fe129b5a/dask-2.0.0-py3-none-any.whl#sha256=3917756ed467ba984a1aa6aa70f213de9014c63945671876698a1621de7f2ac2 (from https://pypi.org/simple/dask/) (requires-python:>=3.5))

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
Error while installing module backend dependencies
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/geonature/core/command/create_gn_module.py", line 80, in install_gn_module
    q = DB.session.query(TModules).filter(TModules.module_code == module_code).one()
  File "/home/geonature/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
[...]
```

**Comment by lpofredc** [comment]
Ok, déjà fixé ici 1f2a40709c579404a6462e18c20e67cd88ca2036 dans la branche develop.
