### ISSUE TITLE
Impossible de terminer un import

### ISSUE THREAD

**Issue by xavyeah39** [PnX-SI/gn_module_import#198]
Lors d'un import d'environ 13000 lignes, je crée un nouveau mapping pour les champs et les nomenclatures.
Tout se passe bien à priori, je reçois le mail de notification pour finir l'import (pas de rapport d'erreurs), mais lorsque que je clique sur "Finir" une erreur apparait et le rapport ne s'affiche pas :

![image](https://user-images.githubusercontent.com/16793813/105027610-423b5400-5a50-11eb-86a2-672040a8b5d7.png)

Dans le fichier de log j'ai : 
```
[2021-01-19 12:12:22 +0100] [4153] [ERROR] Error handling request /import/getValidData/12
Traceback (most recent call last):
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/MONUSER/geonature/backend/server.py", line 39, in __call__
    return self.app(environ, start_response)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/MONUSER/geonature/backend/geonature/core/gn_permissions/decorators.py", line 74, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/MONUSER/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 23, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/MONUSER/geonature/external_modules/import/backend/routes/preview.py", line 64, in get_valid_data
    selected_cols,
  File "/home/MONUSER/geonature/external_modules/import/backend/data_preview/preview.py", line 74, in get_preview
    syn_targets = modified_dict[key]
KeyError: '_tr_id_nomenclature_geo_object_nature_nomenclature_geo_object_n'
```

Et dans les logs postgresql (même erreur répétée sur toutes les tables commençant par "_tr_" : 
```
2021-01-19 12:01:19.802 CET [10491] MYPGUSER@geonature2db ERREUR:  la colonne « _tr_id_nomenclature_blurring_nomenclature_blurring » de la relation « i_pilat_2020_11 » existe déjà
2021-01-19 12:01:19.802 CET [10491] MYPGUSER@geonature2db INSTRUCTION :
                ALTER TABLE gn_imports.i_pilat_2020_11
                ADD COLUMN _tr_id_nomenclature_blurring_nomenclature_blurring character varying(5);
```

Merci d'avance pour vos lumières !

**Comment by xavyeah39** [comment]
Je précise que j'ai déjà fait des imports qui ont fonctionné (avec beaucoup moins de données et de correspondances de nomenclatures cependant).

**Comment by DonovanMaillard** [comment]
Vu avec Xavier à l'instant. Certains champs ont des noms qui sont très longs et se semblent être tronqués à certains endroits du processus. C'est notamment vrai quand le champs source a un intitulé long (code_nomenclature_geo_nature_object par exemple). A voir si ça vient d'ici ...

**Comment by xavyeah39** [comment]
Vu avec Théo dans la foulée ;) 
A priori c'est bien un soucis d'intitulés trop longs lors de la création des colonnes préfixées "_tr_" lors du mapping.
Cela se produit pour les colonnes dont les noms sont déjà un peu long (sur les champs de nomenclatures) dans le fichier à importer (ex : "nomenclature_geo_object_nature"), 
En supprimant le préfixe "nomenclature_" de ces intitulés de champs dans mon fichier source, je n'ai plus de soucis. L'erreur disparait et j'ai bien accès à l'étape 4 permettant de terminer l'import.

Merci @DonovanMaillard et @TheoLechemia !

**Comment by TheoLechemia** [comment]
Résolu avec un hack peu satisfaisant... :
Les champs trop longs pour postgresql sont en effet tronqués. On peut toujours requêter avec le nom long (SELECT my_long_column_name), mais le résultat renvoie le nom tronqué. Ceci provoque une erreur quand on veut récupérer les champs de nomenclature, que l'on a préalablement enregistré (avec le nom long).
Il n'est pas vraiment envisageable de réduire le nom des champs sans avoir des risques de collision.
J'ai donc recréer un dictionnaire avec les noms de champs originaux (long), pour solutionner le problème
