### ISSUE TITLE
Erreur à l'installation sur une installation GeoNature 2.6.0

### ISSUE THREAD

**Issue by sallib** [PnX-SI/gn_module_import#208]
Lors de l'installation du module (v1.1.1) échoue sur une install fraiche de GeoNature (v2.6.0), avec le message suivant :

Commande lancée: `geonature install_gn_module /home/geonatureadmin/gn_modules/gn_module_import import`
```
 install_gn_module  OK
cannot import name 'ModelCruvedAutorization' from 'geonature.core.utils' (/home/geonatureadmin/geonature/backend/geonature/core/utils.py)
Module IMPORT
                    File /home/geonatureadmin/gn_module_import/backend/blueprint.py must have a variable call :
                        blueprint instance of Blueprint

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 80, in install_gn_module
    DB.session.query(TModules).filter(TModules.module_code == module_code).one()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3473, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/utils/gn_module_import.py", line 226, in check_codefile_validity
    from backend.blueprint import blueprint
  File "/home/geonatureadmin/gn_module_import/backend/blueprint.py", line 8, in <module>
    from .routes import (
  File "/home/geonatureadmin/gn_module_import/backend/routes/checks_and_transformations.py", line 7, in <module>
    from ..db.models import TImports
  File "/home/geonatureadmin/gn_module_import/backend/db/models.py", line 12, in <module>
    from geonature.core.utils import ModelCruvedAutorization
ImportError: cannot import name 'ModelCruvedAutorization' from 'geonature.core.utils' (/home/geonatureadmin/geonature/backend/geonature/core/utils.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 94, in install_gn_module
    check_codefile_validity(module_path, module_code)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/gn_module_import.py", line 234, in check_codefile_validity
    module_code, gn_file
geonature.utils.errors.GeoNatureError: Module IMPORT
                    File /home/geonatureadmin/gn_module_import/backend/blueprint.py must have a variable call :
                        blueprint instance of Blueprint


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 132, in install_gn_module
    "Error during module {} installation".format(module_code)
geonature.utils.errors.GeoNatureError: Error during module IMPORT installation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 3, in <module>
    geonature.core.command.main()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 145, in install_gn_module
    if fresh_install:
UnboundLocalError: local variable 'fresh_install' referenced before assignment
```

**Comment by TheoLechemia** [comment]
Bonjour,
Vous-êtes sûr d'avoir installé la version 2.6.0 de GeoNature? 
`cannot import name 'ModelCruvedAutorization' from 'geonature.core.utils' (/home/geonatureadmin/geonature/backend/geonature/core/utils.py)`
La classe `ModelCruvedAutorization` n'est présente que depuis la 2.6.0
et le bug concernant `UnboundLocalError: local variable 'fresh_install' referenced before assignment` a également été corrigée dans cette version.
En ce plaçant dans le répertoire `geonature`, que trouvez vous dans le fichier `VERSION` ?

**Comment by sallib** [comment]
Bonjour, 
Effectivement, je n'étais pas sur la bonne version de Geonature. J'ai fais la migration, ça fonctionne correctement. 
Merci !
