### ISSUE TITLE
Erreur sur mapping enregistré en V1.20

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_module_import#432]
**Version actuelle 2.0.4**
**version précédente 1.2.0**

Suite à un passage en V2,  une erreur survient à la fin d'un import
![image](https://user-images.githubusercontent.com/10024739/221182065-5d08e873-7ca6-4999-85a3-e33fca8c7c49.png)
L’import de données est bloqué à la phase « validation »
![image](https://user-images.githubusercontent.com/10024739/221182239-8f616d14-45b6-4007-a944-f56181684eba.png)

D'après les logs ci-dessous, l'erreur semble venir de l'usage ou de la modification d'un mapping (enregistré en V1), avec la clé `METH_DETERMIN` en cause. 

Une idée pour contourner ou corriger le soucis ?

```
[cac7069e-7ba1-4123-8d91-91c499ef8df5] Exception on /import/contentmappings/6/ [POST]
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonature/geonature/backend/geonature/core/gn_permissions/decorators.py", line 84, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonature/gn_module_import/backend/gn_module_import/routes/mappings.py", line 126, in update_mapping
    mapping.values[key].update(value)
KeyError: 'METH_DETERMIN'
[2023-02-22 15:48:25 +0100] [63708] [ERROR] Exception on /import/contentmappings/6/ [POST]
Traceback (most recent call last):
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonature/geonature/backend/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/geonature/geonature/backend/geonature/core/gn_permissions/decorators.py", line 84, in __check_cruved_scope
    return fn(*args, **kwargs)
  File "/home/geonature/gn_module_import/backend/gn_module_import/routes/mappings.py", line 126, in update_mapping
    mapping.values[key].update(value)
KeyError: 'METH_DETERMIN'

```

**Comment by bouttier** [comment]
Bonjour Gil,
Il semble effectivement il y avoir un bug, tu peux essayer ce fix : https://github.com/PnX-SI/gn_module_import/pull/435

**Comment by gildeluermoz** [comment]
Elie, Merci pour ce correctif.
On test et on te dis si le pb est résolu.

**Comment by gildeluermoz** [comment]
C'est bon, le correctif fonctionne. L'import a passé la phase validation.
Merci pour la réactivité.
