### ISSUE TITLE
Erreur d'installation (v2.1.0) sur GeoNature 1.12.3

### ISSUE THREAD

**Issue by LudmillaT** [PnX-SI/gn_module_import#461]
Bonjour, 

En pleine installation de GeoNature (v 1.12.3) sur un serveur Debian 11, nous voulions installer les modules Import Dashboard et Export. Aucun problème rencontrer lors de l'instalation d'Export (v1.5.1) et de Dashboard(v1.3.0). Cependant l'installation d'Import (v2.1.0) me renvoie l'erreur suivante : 

```
 geonature install-gn-module ~/gn_module_import IMPORT
Installation du backend…
Obtaining file:///home/geonatureadmin/gn_module_import
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting pandas<1.4 (from gn-module-import==2.1.0)
  Using cached pandas-1.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Collecting pyproj<3 (from gn-module-import==2.1.0)
  Using cached pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          bint free_context_on_error,
      ) except *:
          """
          Setup the context for pyproj
          """
          proj_log_func(context, NULL, pyproj_log_function)
                                       ^
      ------------------------------------------------------------

      pyproj/_datadir.pyx:40:33: Cannot assign type 'void (void *, int, const char *) except *' to 'PJ_LOG_FUNCTION'

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  proj_context_destroy(context)
              raise


      def pyproj_global_context_initialize():
          proj_log_func(NULL, NULL, pyproj_log_function)
                                    ^
      ------------------------------------------------------------

      pyproj/_datadir.pyx:52:30: Cannot assign type 'void (void *, int, const char *) except *' to 'PJ_LOG_FUNCTION'
      Traceback (most recent call last):
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-b7du4vp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-b7du4vp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-b7du4vp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-b7du4vp6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 243, in <module>
        File "<string>", line 159, in get_extension_modules
        File "/tmp/pip-build-env-b7du4vp6/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-b7du4vp6/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyproj/_datadir.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 34, in install_gn_module
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/geonatureadmin/gn_module_import'' returned non-zero exit status 1.

```

Je crois comprendre que l'erreur vient du fichier `requirements.in` mais je ne vois pas comment réparer ça, si l'un d'entre vous à une idée de ce qu'il faut faire je suis preneuse. 

Merci d’avance pour vos retours.

**Comment by camillemonchicourt** [comment]
On a fait des changements au niveau des versions de pyproj dans la 1.5.1 : https://github.com/PnX-SI/gn_module_import/pull/452

Pour préparer la compatibilité de GeoNature avec Debian 12.
Normalement ça ne devrait pas poser de soucis sur Debian 11 et on avait testé de mémoire, mais ton soucis semble en lien.

@theo-lechemia, un avis ?

**Comment by TheoLechemia** [comment]
J'ai testé cette semaine d'installer le module d'import sur un debian 11 et j'ai du virer le "pinning" de `pyproj` dans le requirements.in (ne pas spécifier la version), et ça a fonctionné.
Par contre ce qui est bizarre, c'est que ça fonctionnait il y a quelques semaines. Du coup je capte pas trop

**Comment by LudmillaT** [comment]
J'ai tenter d'installer le module sans spécifier la version de `pyproj`, j'ai `gn_imports` qui arrive dans la base de données mais n'rien est visible sur l'application en ligne et je termine avec cette erreur :
```
Rebuild du frontend terminé.
Installation / mise à jour de la base de données…
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 86, in install_gn_module
    if not module_db_upgrade(module_dist, x_arg=x_arg):
  File "/home/geonatureadmin/geonature/backend/geonature/utils/module.py", line 90, in module_db_upgrade
    module_blueprint = module_dist.entry_points["blueprint"].load()  # force discovery of models
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/geonatureadmin/gn_module_import/backend/gn_module_import/blueprint.py", line 3, in <module>
    import gn_module_import.admin  # noqa: F401
  File "/home/geonatureadmin/gn_module_import/backend/gn_module_import/admin.py", line 9, in <module>
    from jsonschema.exceptions import ValidationError as JSONValidationError
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/jsonschema/exceptions.py", line 14, in <module>
    from attrs import define
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/attrs/__init__.py", line 3, in <module>
    from attr import (
ImportError: cannot import name 'AttrsInstance' from 'attr' (/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/attr/__init__.py)

```

**Comment by TheoLechemia** [comment]
J'ai également eu la même erreur sur debian 11... Je pensais que c'était mon contexte un peu particulier qui avait entrainé ces erreurs.
Solutionné avec un `pip install attr` dans le virtualenv de geonature.

On va refaire des tests d'installation sur debian 11. Merci pour les retours

**Comment by LudmillaT** [comment]
Yes ça a marché ! Merci !

**Comment by amandine-sahl** [comment]
Il faudrait modifier le requirements.in pour prendre en compte debian 11

Proposition de @bouttier 
```sh
pyproj<3; python_version<"3.9"  # last version compat. with PROJ 5.2.0 provided by Debian 10
pyproj<3.1; python_version>="3.9",<"3.10"  # last version compat. with PROJ 7.2.1 provided by Debian 11
pyproj; python_version>="3.10"
```

**Comment by gildeluermoz** [comment]
J'ai testé de mettre les 3 lignes proposées par @bouttier mais il me lève une erreur 

```
Installation du module import …
Installation du backend…
Obtaining file:///home/slemadmin/gn_module_import
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in gn_module_import setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end of dependency specifier
          pyproj<3.1; python_version>="3.9",<"3.10"
                                           ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/home/slemadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/slemadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/slemadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 34, in install_gn_module
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/slemadmin/gn_module_import'' returned non-zero exit status 1.
Installation du module occtax …
```
Comme je suis en debian 11 et python 3.9, j'ai mis uniquement ceci : 

`pyproj<3.1; python_version>="3.9"  # last version compat. with PROJ 7.2.1 provided by Debian 11`

pyproj 3.0.1 s'est installé et l'install s'est passé normalement.

**Comment by camillemonchicourt** [comment]
Cela a été corrigé dans la branche DEVELOP, et sera donc OK dans la prochaine release : https://github.com/PnX-SI/gn_module_import/commit/a02943379ca3e8eb57fa5dddd8095cf7afe1df5a

**Comment by camillemonchicourt** [comment]
OK dans la 2.2.0

**Comment by Vottana** [comment]
Bonjour à tous, 
j'ai exactement (enfin je crois) le même problème cité plus haut. (Debian 11, GN 2.12.3, module Import 2.1.0)
Je suis aussi apparemment en python 3.9, mais je ne comprends pas le message d'Amandine et de Gildeluermoz :


> Il faudrait modifier le requirements.in pour prendre en compte debian 11
> Proposition de @bouttier
> ```shell
> pyproj<3; python_version<"3.9"  # last version compat. with PROJ 5.2.0 provided by Debian 10
> pyproj<3.1; python_version>="3.9",<"3.10"  # last version compat. with PROJ 7.2.1 provided by Debian 11
> pyproj; python_version>="3.10"
> ```
> J'ai testé de mettre les 3 lignes proposées par @bouttier mais il me lève une erreur
> Comme je suis en debian 11 et python 3.9, j'ai mis uniquement ceci :
> `pyproj<3.1; python_version>="3.9" # last version compat. with PROJ 7.2.1 provided by Debian 11`
> pyproj 3.0.1 s'est installé et l'install s'est passé normalement.

où dois-je taper ces commandes ? Dans le venv de Geonature ?
Merci d'avance !

Ci-dessous les messages lors de l'installation :

```
(venv) geonatureadmin@ns307:~$ geonature install-gn-module ~/gn_module_import IMPORT
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
  util.warn(
Installation du backend…
Obtaining file:///home/geonatureadmin/gn_module_import
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting pandas<1.4 (from gn-module-import==2.1.0)
  Using cached pandas-1.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Collecting pyproj<3 (from gn-module-import==2.1.0)
  Using cached pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          bint free_context_on_error,
      ) except *:
          """
          Setup the context for pyproj
          """
          proj_log_func(context, NULL, pyproj_log_function)
                                       ^
      ------------------------------------------------------------

      pyproj/_datadir.pyx:40:33: Cannot assign type 'void (void *, int, const char *) except *' to 'PJ_LOG_FUNCTION'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *) except *'.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  proj_context_destroy(context)
              raise


      def pyproj_global_context_initialize():
          proj_log_func(NULL, NULL, pyproj_log_function)
                                    ^
      ------------------------------------------------------------

      pyproj/_datadir.pyx:52:30: Cannot assign type 'void (void *, int, const char *) except *' to 'PJ_LOG_FUNCTION'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *) except *'.
      Traceback (most recent call last):
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-sxxriqix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-sxxriqix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-sxxriqix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-sxxriqix/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 243, in <module>
        File "<string>", line 159, in get_extension_modules
        File "/tmp/pip-build-env-sxxriqix/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-sxxriqix/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyproj/_datadir.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 34, in install_gn_module
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/geonatureadmin/gn_module_import'' returned non-zero exit status 1.
```
Rien ne s'est installé dans la base de données.
En lisant les messages, j'ai tenté : 
- `pip install attr` dans le venv de geonature
```
Requirement already satisfied: attr in ./geonature/backend/venv/lib/python3.9/site-packages (0.3.2)
[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
```
Mais toujours cette erreur : 
```
(venv) geonatureadmin@ns307:~$ geonature install-gn-module ~/gn_module_import IMPORT
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
  util.warn(
Installation du backend…
Obtaining file:///home/geonatureadmin/gn_module_import
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting pandas<1.4 (from gn-module-import==2.1.0)
  Using cached pandas-1.3.5-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
Collecting pyproj<3 (from gn-module-import==2.1.0)
  Using cached pyproj-2.6.1.post1.tar.gz (545 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      <string>:8: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          bint free_context_on_error,
      ) except *:
          """
          Setup the context for pyproj
          """
          proj_log_func(context, NULL, pyproj_log_function)
                                       ^
      ------------------------------------------------------------

      pyproj/_datadir.pyx:40:33: Cannot assign type 'void (void *, int, const char *) except *' to 'PJ_LOG_FUNCTION'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *) except *'.

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  proj_context_destroy(context)
              raise


      def pyproj_global_context_initialize():
          proj_log_func(NULL, NULL, pyproj_log_function)
                                    ^
      ------------------------------------------------------------

      pyproj/_datadir.pyx:52:30: Cannot assign type 'void (void *, int, const char *) except *' to 'PJ_LOG_FUNCTION'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *) except *'.
      Traceback (most recent call last):
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-dj2d4yq5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-dj2d4yq5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-dj2d4yq5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-dj2d4yq5/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 243, in <module>
        File "<string>", line 159, in get_extension_modules
        File "/tmp/pip-build-env-dj2d4yq5/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-dj2d4yq5/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyproj/_datadir.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 34, in install_gn_module
    subprocess.run(f"pip install -e '{module_path}'", shell=True, check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'pip install -e '/home/geonatureadmin/gn_module_import'' returned non-zero exit status 1.

```

**Comment by gildeluermoz** [comment]
C'est dans ce fichier :
https://github.com/PnX-SI/gn_module_import/blob/master/requirements.in
Il faut s'inspirer de ce qui est proposé dans le fichier concernant pyproj.

Désolé, je ne trouve pas le message sur le lien view it on github. Supprimé
?

**Comment by Vottana** [comment]
Bonjour et merci pour ta réponse. 
Oui j'ai supprimé mon message juste après l'avoir posté, car j'ai réalisé que l'issue était fermée mais surtout, parce que j'ai compris juste après où était ce fichier requirements.in : simplement dans le dossier d'installation gn_module_import.
J'ai changé la partie `pyproj` par ce que tu avais mis et l'installation est allée jusqu'au bout. Pas encore fait de test d'import mais mon module est bien là. :)
Bonne journée à tous
